from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];F=json.loads((R/'figure-data.json').read_text());S=json.loads((R/'analysis-summary.json').read_text());assert len(F)==42 and S['cases']==92
cards=[]
for i,f in enumerate(F,1):
 key=f['id'];cards.append(f'''<article data-group="{html.escape(f['group'])}"><div class="tag">{i:02d} / {html.escape(f['group'])}</div><h2>{html.escape(f['title'])}</h2><a href="figures/{key}.svg" target="_blank"><img loading="lazy" src="figures/{key}.png" alt="{html.escape(f['title'])}"></a><details><summary>What this comparison shows</summary><p>{html.escape(f['note'])}</p></details><div class="downloads"><a href="figures/{key}.svg">Vector SVG</a><a href="figures/{key}.png">PNG</a></div></article>''')
groups=list(dict.fromkeys(f['group'] for f in F));options=''.join(f'<option>{html.escape(g)}</option>' for g in groups)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>MIT OR / RASAero coefficient atlas</title><style>
:root{color-scheme:light;font-family:Georgia,serif;color:#15253c;background:#f5f5f2}body{margin:0}header{padding:38px max(5vw,22px) 26px;background:#fff;border-top:8px solid #af1f39;border-bottom:1px solid #ddd}h1{font-weight:normal;font-size:38px;margin:4px 0 12px;letter-spacing:-.6px}header p{max-width:880px;line-height:1.6}.meta{font:14px system-ui;letter-spacing:.05em;text-transform:uppercase;color:#646976}a{color:#08357e}.controls{position:sticky;top:0;background:#fafaf8ed;backdrop-filter:blur(8px);padding:14px 5vw;border-bottom:1px solid #ddd;display:flex;gap:12px;z-index:2;align-items:center;flex-wrap:wrap}input,select{font:15px system-ui;padding:10px 14px;border:1px solid #bcc1c9;border-radius:5px;background:white}input{min-width:280px}#count{font:14px system-ui;color:#555;margin-left:auto}main{max-width:1500px;margin:auto;padding:28px 3vw;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}article{background:white;border:1px solid #deded7;border-radius:7px;padding:20px;box-shadow:0 3px 12px #00000005}.tag{font:11px system-ui;letter-spacing:.08em;text-transform:uppercase;color:#7a0101}h2{font-size:22px;font-weight:normal;margin:10px 0}img{width:100%;height:auto}details{font-size:14px;line-height:1.5;margin:12px 0;color:#45515e}summary{cursor:pointer}.downloads{font:13px system-ui;display:flex;gap:18px}.filelinks{display:flex;gap:20px;flex-wrap:wrap;font:14px system-ui}footer{padding:30px 5vw;font:14px system-ui;line-height:1.5;border-top:1px solid #ddd}article[hidden]{display:none}@media(max-width:850px){main{grid-template-columns:1fr}h1{font-size:28px}input{min-width:190px}}
</style><header><div class="meta">MIT Rocket Team / simulation studies / 27 September 2026</div><h1>OpenRocket &amp; RASAero coefficient atlas</h1><p>92 configurations, 82,800 common Mach/angle points, and 42 plot sheets. The installed MIT OpenRocket engine is unchanged. All RASAero sweeps were collected through its Windows GUI. Each comparison identifies the settings and any analytical reconstruction.</p><div class="filelinks"><a href="../../output/pdf/mit-or-rasaero-study.pdf">Full report (PDF)</a><a href="../../mit-or-rasaero-study.tex">LaTeX source</a><a href="matched-coefficients.csv">Coefficient data</a><a href="error-metrics.csv">Error metrics</a><a href="README.md">Methods &amp; reproduction</a></div></header><div class="controls"><input id="search" placeholder="Search plots…" aria-label="Search plots"><select id="group" aria-label="Study group"><option>All investigations</option>OPTIONS</select><span id="count"></span></div><main>CARDS</main><footer>CD and CL use wind axes; CA and CN use body axes. CP is measured from the nose tip in body diameters. Raw RASAero CL follows the power-on convention when nozzle area is nonzero; the plotted coast lift is reconstructed consistently. Agreement between programs is not validation against measured flight or wind-tunnel data.</footer><script>
const cards=[...document.querySelectorAll('article')],q=document.querySelector('#search'),g=document.querySelector('#group'),count=document.querySelector('#count');function filter(){let n=0;cards.forEach(c=>{c.hidden=!((g.value==='All investigations'||c.dataset.group===g.value)&&c.innerText.toLowerCase().includes(q.value.toLowerCase()));if(!c.hidden)n++;});count.textContent=n+' of '+cards.length+' plot sheets';}q.addEventListener('input',filter);g.addEventListener('change',filter);filter();
</script></html>'''.replace('OPTIONS',options).replace('CARDS',''.join(cards))
(R/'index.html').write_text(page);print('Gallery',len(F),'sheets',sum(len(f['panels']) for f in F),'panels')
