ODB\+\+=Z:\Developer\MIT_Rkt_Team\2026-7\MIT-RT-26_27-Work\simulation_work\avionics\powerboardsim\1\powerboardsim_v1_files\dp0\global\SHER\SHER\PCB_sim_1\PCB1\_METADATA\ecad\PCB1.tgz
ccaBOM=comp-bot.odb|comp-top.odb
ccaBOM_comp-bot.odb=PickPlace_comp-bot.odb
ccaBOM_comp-top.odb=PickPlace_comp-top.odb
ccaFEAModelID=Pfde11776
ccaName=PCB1
dfltPartTemp=0
dfltPartTempUnits=C
dfltStencilThickness=0.127
dfltStencilThicknessUnits=MM
drillEnabled=ENABLED
drillMaxEdge=1
drillMaxEdgeUnits=mm
drillMinDiam=1
drillMinDiamUnits=mm
guessLeadBendRadii242=false
guessLeadFramePercentage=false
guessLeadStiffness=false
guessOvermold=false
guessPackageComplianceFactor=false
guessPartProperties=YES
guessSolderDesignFactor=false
guessSolderModel=false
guessSolderThickness=false
guessWeightState=false
leadElemOrder=First Order
leadMaxEdgeLength=2
leadMaxEdgeLengthUnits=mm
leadMaxVertical=0
leadMaxVerticalUnits=mm
mechanicalPartsElemOrder=First Order
mechanicalPartsEnabled=DISABLED
mechanicalPartsMaxEdgeLength=2
mechanicalPartsMaxEdgeLengthUnits=mm
mechanicalPartsMaxVertical=0
mechanicalPartsMaxVerticalUnits=mm
modelLeads=DISABLED
modelType=Bonded
modelingRegionEnabled=DISABLED
mountPtElemOrder=First Order
mountPtEnabled=ENABLED
mountPtMaxEdgeLength=2
mountPtMaxEdgeLengthUnits=mm
mountPtMaxVertical=0
mountPtMaxVerticalUnits=mm
partElemOrder=First Order
partEnabled=ENABLED
partMaxEdgeLength=1.0
partMaxEdgeLengthUnits=mm
partMaxVertical=0
partMaxVerticalUnits=mm
partMinSize=0
partMinSizeUnits=mm
partResultsFiltered=DISABLED
pcbElemOrder=First Order
pcbMaterialModel=Uniform
pcbMaxEdgeLength=2.0
pcbMaxEdgeLengthUnits=mm
pcbMaxMaterials=100
pcbMaxVertical=0
pcbMaxVerticalUnits=mm
polylineSimplification=DISABLED
polylineTolerance=0.1
polylineToleranceUnits=mm
pottingElemOrder=First Order
pottingEnabled=DISABLED
pottingMaxEdgeLength=2
pottingMaxEdgeLengthUnits=mm
pottingMaxVertical=0
pottingMaxVerticalUnits=mm
quadsPreferred=YES
selected_Layer Viewer=__NONE__
setLeadGeometry=false
sinkElemOrder=First Order
sinkEnabled=DISABLED
sinkMaxEdgeLength=2
sinkMaxEdgeLengthUnits=mm
sinkMaxVertical=0
sinkMaxVerticalUnits=mm
traceElemOrder=First Order
traceEnabled=DISABLED
traceMaxEdgeLength=2.0
traceMaxEdgeLengthUnits=mm
traceMaxHoles=50
treeState_Layer Viewer=Components|Components/comp-top|Drill Holes|Drill Holes/drill-01.odb|Drill Holes/drill-02.odb|Mechanical|Mechanical/Wire Bonds|Mechanical/Assemblies|Mechanical/Cutouts|Mechanical/Mount Points|Mechanical/ICT Fixtures|Mechanical/Accelerometers|Other Layers|Other Layers/OUTLINE|Other Layers/Modeling Regions
updateComponentTechnology=false
wireElemOrder=First Order
wireEnabled=DISABLED
wireMaxEdgeLength=2
wireMaxEdgeLengthUnits=mm
