appendFile=true
copperLayerIndex=3
copperPercent=19.8
fileName=copper-04.odb
fileType=Copper Layer (ODB++)
layerPolarity=POSITIVE
sourceFile=Z:/Developer/MIT_Rkt_Team/2026-7/MIT-RT-26_27-Work/simulation_work/avionics/powerboardsim/1/powerboardsim_v1_files/dp0/global/SHER/SHER/PCB_sim_1/PCB1/copper-04.odb
successMsg=Successfully added a layer representing the data in this file
useLayerThickness=true
