MatId=ARG1
/PREP7
Temperature = 'TEMP' ! Temperature
MP,DENS,MatId,2.77e-09,	! tonne mm^-3
MP,ALPX,MatId,2.3e-05,	! C^-1
MP,C,MatId,875000000,	! mm^2 s^-2 C^-1
MPTEMP,,,,,,,,
MPTEMP,1,-100
MPTEMP,2,0
MPTEMP,3,100
MPTEMP,4,200
MPDATA,KXX,MatId, ,114,144,165,175,	! tonne mm s^-3 C^-1
MPTEMP,,,,,,,,
MPTEMP,1,0
MPTEMP,2,20
MPTEMP,3,100
MPDATA,RSVX,MatId, ,2.43e-05,2.67e-05,3.63e-05,	! ohm mm
MPTEMP,,,,,,,,
MP,EX,MatId,71000,	! tonne s^-2 mm^-1
MP,NUXY,MatId,0.33,
MP,MURX,MatId,1,

