
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071426
     no. of nonzeroes in lower triangle of a =        78451842
     no. of nonzeroes in the factor l        =       777596319
     ratio of nonzeroes in factor (min/max)  =          0.4797
     number of super nodes                   =           26115
     maximum order of a front matrix         =            6111
     maximum size of a front matrix          =        18675216
     maximum size of a front trapezoid       =        13139088
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.3986D+12
     no. of floating point ops for solve     =      9.0456D+09
     ratio of flops for factor (min/max)     =          0.6450
     ratio of allocated memory (max/min)     =          1.8642
     number of positive pivots               =         1071426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.015625        0.027000
     time (cpu & wall) for ordering          =        5.796875        6.577000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        3.609375        4.002000
     time (cpu & wall) for numeric factor    =       26.312500       29.249000
     computational rate (gflops) for factor  =       53.154074       47.817586
     time (cpu & wall) for numeric solve     =        0.296875        0.321000
     computational rate (gflops) for solve   =       30.469410       28.179458
     effective I/O rate (GB/sec) for solve   =      113.516408      104.984995

     no input or output performed

  Solver Memory allocated on core    0       =      803.225 MB
  Solver Memory allocated on core    1       =      625.030 MB
  Solver Memory allocated on core    2       =     1001.700 MB
  Solver Memory allocated on core    3       =      724.533 MB
  Solver Memory allocated on core    4       =      586.830 MB
  Solver Memory allocated on core    5       =      830.058 MB
  Solver Memory allocated on core    6       =      681.365 MB
  Solver Memory allocated on core    7       =      622.047 MB
  Solver Memory allocated on core    8       =     1093.953 MB
  Solver Memory allocated on core    9       =      647.517 MB
  Solver Memory allocated on core   10       =      633.139 MB
  Solver Memory allocated on core   11       =      818.753 MB
  Total Solver Memory allocated by all cores =     9068.150 MB

