3DViewerColorScheme=NF 1,282.28 Hz
3DViewerDividerLocation=200
3DViewerFeatures=Lines|Mechanical Parts|PCB|Other Elements|Mounts|Heat Sinks|Parts|Faces|Leads|Wire Bonds|Potting
3DViewerOptions_3dAxis=Enabled
3DViewerOptions_bgColor=White
3DViewerOptions_colorValue=AVG
3DViewerOptions_displayMode=Coarse
3DViewerOptions_lineMode=Outline
3DViewerOptions_warpFactor=0
3DViewerWindowHeight=799
3DViewerWindowWidth=900
3DViewerWindowX=35
3DViewerWindowY=47
FEA3DViewer-RecentOpened=Z:\Developer\MIT_Rkt_Team\2026-7\MIT-RT-26_27-Work\simulation_work\avionics\powerboardsim\1\powerboardsim_v1_files\dp0\global\SHER\SHER\PCB_sim_1\PCB1\modules\NaturalFreq\Results.dfr-3d;Z:\Developer\MIT_Rkt_Team\2026-7\MIT-RT-26_27-Work\simulation_work\avionics\powerboardsim\1\powerboardsim_v1_files\dp0\global\SHER\SHER\PCB_sim_1\PCB1\modules\NaturalFreq\model.inp;C:\Users\mdn\AppData\Local\Temp\WB_mdn_6072_2\wbnew_files\dp0\global\SHER\SHER\PCB_sim_1\PCB1\modules\NaturalFreq\model.inp;C:\Users\mdn\AppData\Local\Temp\WB_mdn_6072_2\wbnew_files\dp0\global\SHER\SHER\testproject\PCB\modules\RandomVibe\Results.dfr-3d;C:\Users\mdn\AppData\Local\Temp\WB_mdn_6072_2\wbnew_files\dp0\global\SHER\SHER\testproject\PCB\modules\RandomVibe\model.inp;C:\Users\mdn\AppData\Local\Temp\WB_mdn_6072_2\wbnew_files\dp0\global\SHER\SHER\testproject\PCB\modules\HarmonicVibe\model.inp;
defaultView=0.8682431421244592|-0.27959764578618007|0.4098524156628479|0.7999999999999999|0.49613893835683387|0.4892958801258151|-0.7172417274099839|-1.4|0.0|0.8260839534591684|0.5635470715364159|1.1000000000000003|0.0|0.0|0.0|1.0
filename=Sherlock3DViewer.properties
