
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071426
     no. of nonzeroes in lower triangle of a =        79190196
     no. of nonzeroes in the factor l        =       810545397
     ratio of nonzeroes in factor (min/max)  =          0.4615
     number of super nodes                   =           26011
     maximum order of a front matrix         =            6582
     maximum size of a front matrix          =        21664653
     maximum size of a front trapezoid       =        13702935
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.5837D+12
     no. of floating point ops for solve     =      3.1460D+09
     ratio of flops for factor (min/max)     =          0.6478
     ratio of allocated memory (max/min)     =          2.0191
     number of positive pivots               =         1071426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.750000        0.749497
     time (cpu & wall) for ordering          =       13.015625       14.074036
     time (cpu & wall) for other matrix prep =        2.625000        2.936267
     time (cpu & wall) for value input       =        1.734375        1.759833
     time (cpu & wall) for matrix distrib.   =        8.609375        8.891423
     time (cpu & wall) for numeric factor    =       75.562500       85.682527
     computational rate (gflops) for factor  =       20.958602       18.483166
     time (cpu & wall) for numeric solve     =        0.609375        0.674288
     computational rate (gflops) for solve   =        5.162699        4.665691
     effective I/O rate (GB/sec) for solve   =       19.234079       17.382433

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        672738.        5. MB
                95-   1        786432.        6. MB        754595.        6. MB
                95-   2       1277952.       10. MB       1252773.       10. MB
                95-   3        917504.        7. MB        894496.        7. MB
                95-   4        622592.        5. MB        608116.        5. MB
                95-   5       1114112.        8. MB       1088076.        8. MB
                95-   6        819200.        6. MB        796497.        6. MB
                95-   7        655360.        5. MB        649855.        5. MB
                95-   8       1146880.        9. MB       1126540.        9. MB
                95-   9        622592.        5. MB        617776.        5. MB
                95-  10        524288.        4. MB        517946.        4. MB
                95-  11        983040.        8. MB        956415.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:      10158080.       78. MB       9935823.       76. MB


  Solver Memory allocated on core    0       =      835.875 MB
  Solver Memory allocated on core    1       =      937.810 MB
  Solver Memory allocated on core    2       =     1338.924 MB
  Solver Memory allocated on core    3       =      851.336 MB
  Solver Memory allocated on core    4       =      681.627 MB
  Solver Memory allocated on core    5       =     1015.447 MB
  Solver Memory allocated on core    6       =      841.160 MB
  Solver Memory allocated on core    7       =      754.463 MB
  Solver Memory allocated on core    8       =     1132.728 MB
  Solver Memory allocated on core    9       =      717.613 MB
  Solver Memory allocated on core   10       =      663.125 MB
  Solver Memory allocated on core   11       =      972.479 MB
  Total Solver Memory allocated by all cores =    10742.586 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071432
     no. of nonzeroes in lower triangle of a =        78910155
     no. of nonzeroes in the factor l        =       805628232
     ratio of nonzeroes in factor (min/max)  =          0.4971
     number of super nodes                   =           25958
     maximum order of a front matrix         =            6090
     maximum size of a front matrix          =        18547095
     maximum size of a front trapezoid       =        12113469
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.5397D+12
     no. of floating point ops for solve     =      6.2730D+09
     ratio of flops for factor (min/max)     =          0.7126
     ratio of allocated memory (max/min)     =          2.4486
     number of positive pivots               =         1071432
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.500000        0.591306
     time (cpu & wall) for ordering          =       12.734375       14.245771
     time (cpu & wall) for other matrix prep =        2.890625        3.058127
     time (cpu & wall) for value input       =        1.312500        1.371549
     time (cpu & wall) for matrix distrib.   =        7.171875        8.467034
     time (cpu & wall) for numeric factor    =       73.734375       81.304081
     computational rate (gflops) for factor  =       20.881354       18.937224
     time (cpu & wall) for numeric solve     =        1.125000        1.204687
     computational rate (gflops) for solve   =        5.575984        5.207144
     effective I/O rate (GB/sec) for solve   =       20.773806       19.399664

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        786432.        6. MB        764679.        6. MB
                95-   1       1048576.        8. MB       1031555.        8. MB
                95-   2       1343488.       10. MB       1334358.       10. MB
                95-   3        884736.        7. MB        876866.        7. MB
                95-   4       1114112.        8. MB       1102864.        8. MB
                95-   5        950272.        7. MB        946323.        7. MB
                95-   6        589824.        4. MB        573848.        4. MB
                95-   7        589824.        4. MB        570668.        4. MB
                95-   8        688128.        5. MB        657283.        5. MB
                95-   9        655360.        5. MB        645189.        5. MB
                95-  10        458752.        4. MB        453096.        3. MB
                95-  11        983040.        8. MB        966134.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:      10092544.       77. MB       9922863.       76. MB


  Solver Memory allocated on core    0       =      984.776 MB
  Solver Memory allocated on core    1       =     1142.435 MB
  Solver Memory allocated on core    2       =     1418.805 MB
  Solver Memory allocated on core    3       =     1014.856 MB
  Solver Memory allocated on core    4       =     1030.151 MB
  Solver Memory allocated on core    5       =      847.483 MB
  Solver Memory allocated on core    6       =      667.490 MB
  Solver Memory allocated on core    7       =      714.895 MB
  Solver Memory allocated on core    8       =      697.063 MB
  Solver Memory allocated on core    9       =      755.635 MB
  Solver Memory allocated on core   10       =      579.438 MB
  Solver Memory allocated on core   11       =      945.234 MB
  Total Solver Memory allocated by all cores =    10798.260 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071432
     no. of nonzeroes in lower triangle of a =        78847794
     no. of nonzeroes in the factor l        =       810418157
     ratio of nonzeroes in factor (min/max)  =          0.5950
     number of super nodes                   =           26084
     maximum order of a front matrix         =            5964
     maximum size of a front matrix          =        17787630
     maximum size of a front trapezoid       =        11350323
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.6033D+12
     no. of floating point ops for solve     =      9.4188D+09
     ratio of flops for factor (min/max)     =          0.7910
     ratio of allocated memory (max/min)     =          2.2188
     number of positive pivots               =         1071432
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        1.609375        1.657389
     time (cpu & wall) for ordering          =       13.093750       14.289921
     time (cpu & wall) for other matrix prep =        2.453125        2.592613
     time (cpu & wall) for value input       =        2.671875        2.721732
     time (cpu & wall) for matrix distrib.   =       14.875000       16.992512
     time (cpu & wall) for numeric factor    =       73.250000       82.379290
     computational rate (gflops) for factor  =       21.887448       19.461876
     time (cpu & wall) for numeric solve     =        1.234375        1.386536
     computational rate (gflops) for solve   =        7.630381        6.793008
     effective I/O rate (GB/sec) for solve   =       28.427640       25.307936

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        917504.        7. MB        888072.        7. MB
                95-   1        884736.        7. MB        864328.        7. MB
                95-   2       1343488.       10. MB       1329213.       10. MB
                95-   3        917504.        7. MB        894560.        7. MB
                95-   4       1081344.        8. MB       1059880.        8. MB
                95-   5        819200.        6. MB        805828.        6. MB
                95-   6        524288.        4. MB        519833.        4. MB
                95-   7        753664.        6. MB        721872.        6. MB
                95-   8        753664.        6. MB        745125.        6. MB
                95-   9        557056.        4. MB        549141.        4. MB
                95-  10        622592.        5. MB        603101.        5. MB
                95-  11        983040.        8. MB        958025.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:      10158080.       78. MB       9938978.       76. MB


  Solver Memory allocated on core    0       =      947.109 MB
  Solver Memory allocated on core    1       =     1037.172 MB
  Solver Memory allocated on core    2       =     1372.242 MB
  Solver Memory allocated on core    3       =     1024.260 MB
  Solver Memory allocated on core    4       =     1043.950 MB
  Solver Memory allocated on core    5       =      784.656 MB
  Solver Memory allocated on core    6       =      618.465 MB
  Solver Memory allocated on core    7       =      813.117 MB
  Solver Memory allocated on core    8       =      763.917 MB
  Solver Memory allocated on core    9       =      682.493 MB
  Solver Memory allocated on core   10       =      729.149 MB
  Solver Memory allocated on core   11       =      965.504 MB
  Total Solver Memory allocated by all cores =    10782.036 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071432
     no. of nonzeroes in lower triangle of a =        78847794
     no. of nonzeroes in the factor l        =       810418157
     ratio of nonzeroes in factor (min/max)  =          0.5950
     number of super nodes                   =           26084
     maximum order of a front matrix         =            5964
     maximum size of a front matrix          =        17787630
     maximum size of a front trapezoid       =        11350323
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.6033D+12
     no. of floating point ops for solve     =      9.4188D+09
     ratio of flops for factor (min/max)     =          0.7910
     ratio of allocated memory (max/min)     =          2.2189
     number of positive pivots               =         1071432
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.703125        0.726819
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        1.421875        1.437649
     time (cpu & wall) for matrix distrib.   =        7.796875        8.601284
     time (cpu & wall) for numeric factor    =       73.250000       80.519957
     computational rate (gflops) for factor  =       21.887448       19.911282
     time (cpu & wall) for numeric solve     =        0.703125        0.853345
     computational rate (gflops) for solve   =       13.395557       11.037443
     effective I/O rate (GB/sec) for solve   =       49.906301       41.120943

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        917504.        7. MB        888072.        7. MB
                95-   1        884736.        7. MB        864328.        7. MB
                95-   2       1343488.       10. MB       1329213.       10. MB
                95-   3        917504.        7. MB        894560.        7. MB
                95-   4       1081344.        8. MB       1059880.        8. MB
                95-   5        819200.        6. MB        805828.        6. MB
                95-   6        524288.        4. MB        519833.        4. MB
                95-   7        753664.        6. MB        721872.        6. MB
                95-   8        753664.        6. MB        745125.        6. MB
                95-   9        557056.        4. MB        549141.        4. MB
                95-  10        622592.        5. MB        603101.        5. MB
                95-  11        983040.        8. MB        958025.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:      10158080.       78. MB       9938978.       76. MB


  Solver Memory allocated on core    0       =      946.309 MB
  Solver Memory allocated on core    1       =     1036.907 MB
  Solver Memory allocated on core    2       =     1372.111 MB
  Solver Memory allocated on core    3       =     1024.260 MB
  Solver Memory allocated on core    4       =     1043.950 MB
  Solver Memory allocated on core    5       =      784.656 MB
  Solver Memory allocated on core    6       =      618.364 MB
  Solver Memory allocated on core    7       =      813.029 MB
  Solver Memory allocated on core    8       =      763.830 MB
  Solver Memory allocated on core    9       =      682.421 MB
  Solver Memory allocated on core   10       =      729.049 MB
  Solver Memory allocated on core   11       =      965.356 MB
  Total Solver Memory allocated by all cores =    10780.242 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071432
     no. of nonzeroes in lower triangle of a =        78847794
     no. of nonzeroes in the factor l        =       810418157
     ratio of nonzeroes in factor (min/max)  =          0.5950
     number of super nodes                   =           26084
     maximum order of a front matrix         =            5964
     maximum size of a front matrix          =        17787630
     maximum size of a front trapezoid       =        11350323
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.6033D+12
     no. of floating point ops for solve     =      9.4188D+09
     ratio of flops for factor (min/max)     =          0.7910
     ratio of allocated memory (max/min)     =          2.2190
     number of positive pivots               =         1071432
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.609375        0.661270
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        1.312500        1.333968
     time (cpu & wall) for matrix distrib.   =        8.218750        8.575207
     time (cpu & wall) for numeric factor    =       75.296875       83.283161
     computational rate (gflops) for factor  =       21.292458       19.250657
     time (cpu & wall) for numeric solve     =        0.859375        0.936025
     computational rate (gflops) for solve   =       10.960002       10.062501
     effective I/O rate (GB/sec) for solve   =       40.832428       37.488711

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        917504.        7. MB        888072.        7. MB
                95-   1        884736.        7. MB        864328.        7. MB
                95-   2       1343488.       10. MB       1329213.       10. MB
                95-   3        917504.        7. MB        894560.        7. MB
                95-   4       1081344.        8. MB       1059880.        8. MB
                95-   5        819200.        6. MB        805828.        6. MB
                95-   6        524288.        4. MB        519833.        4. MB
                95-   7        753664.        6. MB        721872.        6. MB
                95-   8        753664.        6. MB        745125.        6. MB
                95-   9        557056.        4. MB        549141.        4. MB
                95-  10        622592.        5. MB        603101.        5. MB
                95-  11        983040.        8. MB        958025.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:      10158080.       78. MB       9938978.       76. MB


  Solver Memory allocated on core    0       =      945.892 MB
  Solver Memory allocated on core    1       =     1036.673 MB
  Solver Memory allocated on core    2       =     1372.044 MB
  Solver Memory allocated on core    3       =     1024.260 MB
  Solver Memory allocated on core    4       =     1043.950 MB
  Solver Memory allocated on core    5       =      784.656 MB
  Solver Memory allocated on core    6       =      618.305 MB
  Solver Memory allocated on core    7       =      812.993 MB
  Solver Memory allocated on core    8       =      763.796 MB
  Solver Memory allocated on core    9       =      682.349 MB
  Solver Memory allocated on core   10       =      728.981 MB
  Solver Memory allocated on core   11       =      965.267 MB
  Total Solver Memory allocated by all cores =    10779.165 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071432
     no. of nonzeroes in lower triangle of a =        78713649
     no. of nonzeroes in the factor l        =       790601904
     ratio of nonzeroes in factor (min/max)  =          0.5187
     number of super nodes                   =           26036
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        15845370
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.4830D+12
     no. of floating point ops for solve     =      1.2486D+10
     ratio of flops for factor (min/max)     =          0.6296
     ratio of allocated memory (max/min)     =          2.2257
     number of positive pivots               =         1071432
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        1.203125        1.209321
     time (cpu & wall) for ordering          =       11.828125       13.009741
     time (cpu & wall) for other matrix prep =        1.937500        2.195828
     time (cpu & wall) for value input       =        2.328125        2.432489
     time (cpu & wall) for matrix distrib.   =       12.156250       13.655106
     time (cpu & wall) for numeric factor    =       60.093750       67.781246
     computational rate (gflops) for factor  =       24.677698       21.878846
     time (cpu & wall) for numeric solve     =        0.765625        0.776381
     computational rate (gflops) for solve   =       16.307977       16.082052
     effective I/O rate (GB/sec) for solve   =       60.756772       59.915069

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        679383.        5. MB
                95-   1        917504.        7. MB        894620.        7. MB
                95-   2       1245184.       10. MB       1220406.        9. MB
                95-   3        557056.        4. MB        556136.        4. MB
                95-   4        557056.        4. MB        542381.        4. MB
                95-   5        753664.        6. MB        734535.        6. MB
                95-   6       1114112.        8. MB       1082468.        8. MB
                95-   7        688128.        5. MB        684316.        5. MB
                95-   8        655360.        5. MB        645267.        5. MB
                95-   9       1081344.        8. MB       1052979.        8. MB
                95-  10        819200.        6. MB        813710.        6. MB
                95-  11       1015808.        8. MB       1014198.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:      10092544.       77. MB       9920399.       76. MB


  Solver Memory allocated on core    0       =      858.535 MB
  Solver Memory allocated on core    1       =     1052.889 MB
  Solver Memory allocated on core    2       =     1266.410 MB
  Solver Memory allocated on core    3       =      569.004 MB
  Solver Memory allocated on core    4       =      636.024 MB
  Solver Memory allocated on core    5       =      670.852 MB
  Solver Memory allocated on core    6       =     1038.880 MB
  Solver Memory allocated on core    7       =      799.158 MB
  Solver Memory allocated on core    8       =      705.408 MB
  Solver Memory allocated on core    9       =     1025.338 MB
  Solver Memory allocated on core   10       =     1028.834 MB
  Solver Memory allocated on core   11       =      987.061 MB
  Total Solver Memory allocated by all cores =    10638.391 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071432
     no. of nonzeroes in lower triangle of a =        78713649
     no. of nonzeroes in the factor l        =       790601904
     ratio of nonzeroes in factor (min/max)  =          0.5187
     number of super nodes                   =           26036
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        15845370
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.4830D+12
     no. of floating point ops for solve     =      1.2486D+10
     ratio of flops for factor (min/max)     =          0.6296
     ratio of allocated memory (max/min)     =          2.2257
     number of positive pivots               =         1071432
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.609375        0.680852
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        1.281250        1.357844
     time (cpu & wall) for matrix distrib.   =        7.765625        8.281983
     time (cpu & wall) for numeric factor    =       70.484375       78.976258
     computational rate (gflops) for factor  =       21.039775       18.777484
     time (cpu & wall) for numeric solve     =        0.859375        0.871306
     computational rate (gflops) for solve   =       14.528925       14.329973
     effective I/O rate (GB/sec) for solve   =       54.128760       53.387547

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        679383.        5. MB
                95-   1        917504.        7. MB        894620.        7. MB
                95-   2       1245184.       10. MB       1220406.        9. MB
                95-   3        557056.        4. MB        556136.        4. MB
                95-   4        557056.        4. MB        542381.        4. MB
                95-   5        753664.        6. MB        734535.        6. MB
                95-   6       1114112.        8. MB       1082468.        8. MB
                95-   7        688128.        5. MB        684316.        5. MB
                95-   8        655360.        5. MB        645267.        5. MB
                95-   9       1081344.        8. MB       1052979.        8. MB
                95-  10        819200.        6. MB        813710.        6. MB
                95-  11       1015808.        8. MB       1014198.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:      10092544.       77. MB       9920399.       76. MB


  Solver Memory allocated on core    0       =      858.599 MB
  Solver Memory allocated on core    1       =     1052.886 MB
  Solver Memory allocated on core    2       =     1266.405 MB
  Solver Memory allocated on core    3       =      569.004 MB
  Solver Memory allocated on core    4       =      636.024 MB
  Solver Memory allocated on core    5       =      670.852 MB
  Solver Memory allocated on core    6       =     1038.877 MB
  Solver Memory allocated on core    7       =      799.158 MB
  Solver Memory allocated on core    8       =      705.404 MB
  Solver Memory allocated on core    9       =     1025.336 MB
  Solver Memory allocated on core   10       =     1028.834 MB
  Solver Memory allocated on core   11       =      987.061 MB
  Total Solver Memory allocated by all cores =    10638.440 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071432
     no. of nonzeroes in lower triangle of a =        78713649
     no. of nonzeroes in the factor l        =       790601904
     ratio of nonzeroes in factor (min/max)  =          0.5187
     number of super nodes                   =           26036
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        15845370
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.4830D+12
     no. of floating point ops for solve     =      1.2486D+10
     ratio of flops for factor (min/max)     =          0.6296
     ratio of allocated memory (max/min)     =          2.2256
     number of positive pivots               =         1071432
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.781250        0.796304
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        1.328125        1.339612
     time (cpu & wall) for matrix distrib.   =        7.578125        8.434196
     time (cpu & wall) for numeric factor    =       75.109375       83.690888
     computational rate (gflops) for factor  =       19.744212       17.719676
     time (cpu & wall) for numeric solve     =        0.812500        0.893372
     computational rate (gflops) for solve   =       15.367132       13.976024
     effective I/O rate (GB/sec) for solve   =       57.251574       52.068880

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        679383.        5. MB
                95-   1        917504.        7. MB        894620.        7. MB
                95-   2       1245184.       10. MB       1220406.        9. MB
                95-   3        557056.        4. MB        556136.        4. MB
                95-   4        557056.        4. MB        542381.        4. MB
                95-   5        753664.        6. MB        734535.        6. MB
                95-   6       1114112.        8. MB       1082468.        8. MB
                95-   7        688128.        5. MB        684316.        5. MB
                95-   8        655360.        5. MB        645267.        5. MB
                95-   9       1081344.        8. MB       1052979.        8. MB
                95-  10        819200.        6. MB        813710.        6. MB
                95-  11       1015808.        8. MB       1014198.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:      10092544.       77. MB       9920399.       76. MB


  Solver Memory allocated on core    0       =      858.601 MB
  Solver Memory allocated on core    1       =     1052.886 MB
  Solver Memory allocated on core    2       =     1266.404 MB
  Solver Memory allocated on core    3       =      569.004 MB
  Solver Memory allocated on core    4       =      636.024 MB
  Solver Memory allocated on core    5       =      670.852 MB
  Solver Memory allocated on core    6       =     1038.877 MB
  Solver Memory allocated on core    7       =      799.158 MB
  Solver Memory allocated on core    8       =      705.404 MB
  Solver Memory allocated on core    9       =     1025.336 MB
  Solver Memory allocated on core   10       =     1028.834 MB
  Solver Memory allocated on core   11       =      987.061 MB
  Total Solver Memory allocated by all cores =    10638.443 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071426
     no. of nonzeroes in lower triangle of a =        78709110
     no. of nonzeroes in the factor l        =       773360652
     ratio of nonzeroes in factor (min/max)  =          0.4040
     number of super nodes                   =           26030
     maximum order of a front matrix         =            5925
     maximum size of a front matrix          =        17555775
     maximum size of a front trapezoid       =        12826425
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.3588D+12
     no. of floating point ops for solve     =      1.5484D+10
     ratio of flops for factor (min/max)     =          0.6136
     ratio of allocated memory (max/min)     =          2.1883
     number of positive pivots               =         1071426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.625000        0.762444
     time (cpu & wall) for ordering          =       13.015625       15.174712
     time (cpu & wall) for other matrix prep =        2.359375        2.796543
     time (cpu & wall) for value input       =        1.234375        1.324108
     time (cpu & wall) for matrix distrib.   =        8.234375        9.538846
     time (cpu & wall) for numeric factor    =       72.609375       79.797872
     computational rate (gflops) for factor  =       18.713161       17.027408
     time (cpu & wall) for numeric solve     =        1.640625        1.831042
     computational rate (gflops) for solve   =        9.437961        8.456472
     effective I/O rate (GB/sec) for solve   =       35.161936       31.505313

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1114112.        8. MB       1109081.        8. MB
                95-   1        983040.        8. MB        974953.        7. MB
                95-   2       1048576.        8. MB       1031424.        8. MB
                95-   3        589824.        4. MB        577645.        4. MB
                95-   4        524288.        4. MB        519576.        4. MB
                95-   5       1114112.        8. MB       1111227.        8. MB
                95-   6        655360.        5. MB        627044.        5. MB
                95-   7        524288.        4. MB        510460.        4. MB
                95-   8        950272.        7. MB        944587.        7. MB
                95-   9       1212416.        9. MB       1185758.        9. MB
                95-  10        688128.        5. MB        687205.        5. MB
                95-  11        655360.        5. MB        637036.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:      10059776.       77. MB       9915996.       76. MB


  Solver Memory allocated on core    0       =     1218.140 MB
  Solver Memory allocated on core    1       =     1040.517 MB
  Solver Memory allocated on core    2       =     1113.773 MB
  Solver Memory allocated on core    3       =      587.679 MB
  Solver Memory allocated on core    4       =      556.673 MB
  Solver Memory allocated on core    5       =      991.717 MB
  Solver Memory allocated on core    6       =      737.411 MB
  Solver Memory allocated on core    7       =      629.757 MB
  Solver Memory allocated on core    8       =      902.240 MB
  Solver Memory allocated on core    9       =     1170.875 MB
  Solver Memory allocated on core   10       =      688.706 MB
  Solver Memory allocated on core   11       =      755.781 MB
  Total Solver Memory allocated by all cores =    10393.268 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071426
     no. of nonzeroes in lower triangle of a =        78709110
     no. of nonzeroes in the factor l        =       773360652
     ratio of nonzeroes in factor (min/max)  =          0.4040
     number of super nodes                   =           26030
     maximum order of a front matrix         =            5925
     maximum size of a front matrix          =        17555775
     maximum size of a front trapezoid       =        12826425
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.3588D+12
     no. of floating point ops for solve     =      1.5484D+10
     ratio of flops for factor (min/max)     =          0.6136
     ratio of allocated memory (max/min)     =          2.1883
     number of positive pivots               =         1071426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.656250        0.672854
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        1.187500        1.334655
     time (cpu & wall) for matrix distrib.   =        7.062500        7.906860
     time (cpu & wall) for numeric factor    =       66.468750       72.048103
     computational rate (gflops) for factor  =       20.441951       18.858941
     time (cpu & wall) for numeric solve     =        0.875000        0.952354
     computational rate (gflops) for solve   =       17.696177       16.258815
     effective I/O rate (GB/sec) for solve   =       65.928630       60.573614

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1114112.        8. MB       1109081.        8. MB
                95-   1        983040.        8. MB        974953.        7. MB
                95-   2       1048576.        8. MB       1031424.        8. MB
                95-   3        589824.        4. MB        577645.        4. MB
                95-   4        524288.        4. MB        519576.        4. MB
                95-   5       1114112.        8. MB       1111227.        8. MB
                95-   6        655360.        5. MB        627044.        5. MB
                95-   7        524288.        4. MB        510460.        4. MB
                95-   8        950272.        7. MB        944587.        7. MB
                95-   9       1212416.        9. MB       1185758.        9. MB
                95-  10        688128.        5. MB        687205.        5. MB
                95-  11        655360.        5. MB        637036.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:      10059776.       77. MB       9915996.       76. MB


  Solver Memory allocated on core    0       =     1218.140 MB
  Solver Memory allocated on core    1       =     1040.517 MB
  Solver Memory allocated on core    2       =     1113.773 MB
  Solver Memory allocated on core    3       =      587.679 MB
  Solver Memory allocated on core    4       =      556.673 MB
  Solver Memory allocated on core    5       =      991.717 MB
  Solver Memory allocated on core    6       =      737.411 MB
  Solver Memory allocated on core    7       =      629.757 MB
  Solver Memory allocated on core    8       =      902.240 MB
  Solver Memory allocated on core    9       =     1170.875 MB
  Solver Memory allocated on core   10       =      688.706 MB
  Solver Memory allocated on core   11       =      755.781 MB
  Total Solver Memory allocated by all cores =    10393.268 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071426
     no. of nonzeroes in lower triangle of a =        78709110
     no. of nonzeroes in the factor l        =       773360652
     ratio of nonzeroes in factor (min/max)  =          0.4040
     number of super nodes                   =           26030
     maximum order of a front matrix         =            5925
     maximum size of a front matrix          =        17555775
     maximum size of a front trapezoid       =        12826425
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.3588D+12
     no. of floating point ops for solve     =      1.5484D+10
     ratio of flops for factor (min/max)     =          0.6136
     ratio of allocated memory (max/min)     =          2.1883
     number of positive pivots               =         1071426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.671875        0.713506
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        1.250000        1.317902
     time (cpu & wall) for matrix distrib.   =        7.406250        8.060252
     time (cpu & wall) for numeric factor    =       74.500000       79.391015
     computational rate (gflops) for factor  =       18.238267       17.114669
     time (cpu & wall) for numeric solve     =        0.812500        0.864640
     computational rate (gflops) for solve   =       19.057422       17.908213
     effective I/O rate (GB/sec) for solve   =       71.000063       66.718588

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1114112.        8. MB       1109081.        8. MB
                95-   1        983040.        8. MB        974953.        7. MB
                95-   2       1048576.        8. MB       1031424.        8. MB
                95-   3        589824.        4. MB        577645.        4. MB
                95-   4        524288.        4. MB        519576.        4. MB
                95-   5       1114112.        8. MB       1111227.        8. MB
                95-   6        655360.        5. MB        627044.        5. MB
                95-   7        524288.        4. MB        510460.        4. MB
                95-   8        950272.        7. MB        944587.        7. MB
                95-   9       1212416.        9. MB       1185758.        9. MB
                95-  10        688128.        5. MB        687205.        5. MB
                95-  11        655360.        5. MB        637036.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:      10059776.       77. MB       9915996.       76. MB


  Solver Memory allocated on core    0       =     1218.140 MB
  Solver Memory allocated on core    1       =     1040.517 MB
  Solver Memory allocated on core    2       =     1113.773 MB
  Solver Memory allocated on core    3       =      587.679 MB
  Solver Memory allocated on core    4       =      556.673 MB
  Solver Memory allocated on core    5       =      991.717 MB
  Solver Memory allocated on core    6       =      737.411 MB
  Solver Memory allocated on core    7       =      629.757 MB
  Solver Memory allocated on core    8       =      902.240 MB
  Solver Memory allocated on core    9       =     1170.875 MB
  Solver Memory allocated on core   10       =      688.706 MB
  Solver Memory allocated on core   11       =      755.781 MB
  Total Solver Memory allocated by all cores =    10393.268 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1071426
     no. of nonzeroes in lower triangle of a =        78709110
     no. of nonzeroes in the factor l        =       773360652
     ratio of nonzeroes in factor (min/max)  =          0.4040
     number of super nodes                   =           26030
     maximum order of a front matrix         =            5925
     maximum size of a front matrix          =        17555775
     maximum size of a front trapezoid       =        12826425
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.3588D+12
     no. of floating point ops for solve     =      1.5484D+10
     ratio of flops for factor (min/max)     =          0.6136
     ratio of allocated memory (max/min)     =          2.1883
     number of positive pivots               =         1071426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.593750        0.594138
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.968750        0.986036
     time (cpu & wall) for matrix distrib.   =        6.125000        6.867249
     time (cpu & wall) for numeric factor    =       62.421875       70.503466
     computational rate (gflops) for factor  =       21.767224       19.272115
     time (cpu & wall) for numeric solve     =        0.578125        0.628475
     computational rate (gflops) for solve   =       26.783403       24.637655
     effective I/O rate (GB/sec) for solve   =       99.783873       91.789701

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1114112.        8. MB       1109081.        8. MB
                95-   1        983040.        8. MB        974953.        7. MB
                95-   2       1048576.        8. MB       1031424.        8. MB
                95-   3        589824.        4. MB        577645.        4. MB
                95-   4        524288.        4. MB        519576.        4. MB
                95-   5       1114112.        8. MB       1111227.        8. MB
                95-   6        655360.        5. MB        627044.        5. MB
                95-   7        524288.        4. MB        510460.        4. MB
                95-   8        950272.        7. MB        944587.        7. MB
                95-   9       1212416.        9. MB       1185758.        9. MB
                95-  10        688128.        5. MB        687205.        5. MB
                95-  11        655360.        5. MB        637036.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:      10059776.       77. MB       9915996.       76. MB


  Solver Memory allocated on core    0       =     1218.140 MB
  Solver Memory allocated on core    1       =     1040.517 MB
  Solver Memory allocated on core    2       =     1113.773 MB
  Solver Memory allocated on core    3       =      587.679 MB
  Solver Memory allocated on core    4       =      556.673 MB
  Solver Memory allocated on core    5       =      991.717 MB
  Solver Memory allocated on core    6       =      737.411 MB
  Solver Memory allocated on core    7       =      629.757 MB
  Solver Memory allocated on core    8       =      902.240 MB
  Solver Memory allocated on core    9       =     1170.875 MB
  Solver Memory allocated on core   10       =      688.706 MB
  Solver Memory allocated on core   11       =      755.781 MB
  Total Solver Memory allocated by all cores =    10393.268 MB

