
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         1072113
     no. of nonzeroes in lower triangle of a =        66948010
     no. of nonzeroes in the factor l        =       687506853
     ratio of nonzeroes in factor (min/max)  =          0.4121
     number of super nodes                   =           26408
     maximum order of a front matrix         =            2391
     maximum size of a front matrix          =         2859636
     maximum size of a front trapezoid       =         1929630
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.0772D+12
     no. of floating point ops for solve     =      2.6578D+09
     ratio of flops for factor (min/max)     =          0.5288
     ratio of allocated memory (max/min)     =          2.2935
     number of positive pivots               =         1072101
     number of negative pivots               =              12
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.000000        0.020000
     time (cpu & wall) for ordering          =       34.375000       37.604000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        6.156250        6.967000
     time (cpu & wall) for numeric factor    =       54.890625       60.480000
     computational rate (gflops) for factor  =       19.624766       17.811106
     time (cpu & wall) for numeric solve     =        0.765625        0.872000
     computational rate (gflops) for solve   =        3.471410        3.047934
     effective I/O rate (GB/sec) for solve   =       12.933038       11.355341

     no input or output performed

  Solver Memory allocated on core    0       =      737.137 MB
  Solver Memory allocated on core    1       =      738.800 MB
  Solver Memory allocated on core    2       =      889.825 MB
  Solver Memory allocated on core    3       =      888.361 MB
  Solver Memory allocated on core    4       =      445.158 MB
  Solver Memory allocated on core    5       =      387.984 MB
  Solver Memory allocated on core    6       =      600.118 MB
  Solver Memory allocated on core    7       =      652.902 MB
  Solver Memory allocated on core    8       =      532.316 MB
  Solver Memory allocated on core    9       =      714.412 MB
  Solver Memory allocated on core   10       =      665.213 MB
  Solver Memory allocated on core   11       =      861.477 MB
  Total Solver Memory allocated by all cores =     8113.704 MB

