Run case 1: alpha -10 beta -10
A a -10
B b -10
D da 0
D de 0
D dr 0

Run case 2: alpha -10 beta -5
A a -10
B b -5
D da 0
D de 0
D dr 0

Run case 3: alpha -10 beta 0
A a -10
B b 0
D da 0
D de 0
D dr 0

Run case 4: alpha -10 beta 5
A a -10
B b 5
D da 0
D de 0
D dr 0

Run case 5: alpha -10 beta 10
A a -10
B b 10
D da 0
D de 0
D dr 0


Run case 6: alpha -5 beta -10
A a -5
B b -10
D da 0
D de 0
D dr 0

Run case 7: alpha -5 beta -5
A a -5
B b -5
D da 0
D de 0
D dr 0

Run case 8: alpha -5 beta 0
A a -5
B b 0
D da 0
D de 0
D dr 0

Run case 9: alpha -5 beta 5
A a -5
B b 5
D da 0
D de 0
D dr 0

Run case 10: alpha -5 beta 10
A a -5
B b 10
D da 0
D de 0
D dr 0


Run case 11: alpha 0 beta -10
A a 0
B b -10
D da 0
D de 0
D dr 0

Run case 12: alpha 0 beta -5
A a 0
B b -5
D da 0
D de 0
D dr 0

Run case 13: alpha 0 beta 0
A a 0
B b 0
D da 0
D de 0
D dr 0

Run case 14: alpha 0 beta 5
A a 0
B b 5
D da 0
D de 0
D dr 0

Run case 15: alpha 0 beta 10
A a 0
B b 10
D da 0
D de 0
D dr 0


Run case 16: alpha 5 beta -10
A a 5
B b -10
D da 0
D de 0
D dr 0

Run case 17: alpha 5 beta -5
A a 5
B b -5
D da 0
D de 0
D dr 0

Run case 18: alpha 5 beta 0
A a 5
B b 0
D da 0
D de 0
D dr 0

Run case 19: alpha 5 beta 5
A a 5
B b 5
D da 0
D de 0
D dr 0

Run case 20: alpha 5 beta 10
A a 5
B b 10
D da 0
D de 0
D dr 0


Run case 21: alpha 10 beta -10
A a 10
B b -10
D da 0
D de 0
D dr 0

Run case 22: alpha 10 beta -5
A a 10
B b -5
D da 0
D de 0
D dr 0

Run case 23: alpha 10 beta 0
A a 10
B b 0
D da 0
D de 0
D dr 0

Run case 24: alpha 10 beta 5
A a 10
B b 5
D da 0
D de 0
D dr 0

Run case 25: alpha 10 beta 10
A a 10
B b 10
D da 0
D de 0
D dr 0


Run case 26: alpha 15 beta -10
A a 15
B b -10
D da 0
D de 0
D dr 0

Run case 27: alpha 15 beta -5
A a 15
B b -5
D da 0
D de 0
D dr 0

Run case 28: alpha 15 beta 0
A a 15
B b 0
D da 0
D de 0
D dr 0

Run case 29: alpha 15 beta 5
A a 15
B b 5
D da 0
D de 0
D dr 0

Run case 30: alpha 15 beta 10
A a 15
B b 10
D da 0
D de 0
D dr 0
