LOAD rocket2.avl
OPER
A A 0
B B 0
D3 D3 5
X
FT runs_tab_angle_+/a0_b0_de5.txt
+
A A 0
B B 5
D3 D3 5
X
FT runs_tab_angle_+/a0_b5_de5.txt
+
A A 0
B B 10
D3 D3 5
X
FT runs_tab_angle_+/a0_b10_de5.txt
+
A A 5
B B 0
D3 D3 5
X
FT runs_tab_angle_+/a5_b0_de5.txt
+
A A 5
B B 5
D3 D3 5
X
FT runs_tab_angle_+/a5_b5_de5.txt
+
A A 5
B B 10
D3 D3 5
X
FT runs_tab_angle_+/a5_b10_de5.txt
+
A A 10
B B 0
D3 D3 5
X
FT runs_tab_angle_+/a10_b0_de5.txt
+
A A 10
B B 5
D3 D3 5
X
FT runs_tab_angle_+/a10_b5_de5.txt
+
A A 10
B B 10
D3 D3 5
X
FT runs_tab_angle_+/a10_b10_de5.txt
+
A A 15
B B 0
D3 D3 5
X
FT runs_tab_angle_+/a15_b0_de5.txt
+
A A 15
B B 5
D3 D3 5
X
FT runs_tab_angle_+/a15_b5_de5.txt
+
A A 15
B B 10
D3 D3 5
X
FT runs_tab_angle_+/a15_b10_de5.txt
+
A A 0
B B 0
D3 D3 3
X
FT runs_tab_angle_+/a0_b0_de3.txt
+
A A 0
B B 5
D3 D3 3
X
FT runs_tab_angle_+/a0_b5_de3.txt
+
A A 0
B B 10
D3 D3 3
X
FT runs_tab_angle_+/a0_b10_de3.txt
+
A A 5
B B 0
D3 D3 3
X
FT runs_tab_angle_+/a5_b0_de3.txt
+
A A 5
B B 5
D3 D3 3
X
FT runs_tab_angle_+/a5_b5_de3.txt
+
A A 5
B B 10
D3 D3 3
X
FT runs_tab_angle_+/a5_b10_de3.txt
+
A A 10
B B 0
D3 D3 3
X
FT runs_tab_angle_+/a10_b0_de3.txt
+
A A 10
B B 5
D3 D3 3
X
FT runs_tab_angle_+/a10_b5_de3.txt
+
A A 10
B B 10
D3 D3 3
X
FT runs_tab_angle_+/a10_b10_de3.txt
+
A A 15
B B 0
D3 D3 3
X
FT runs_tab_angle_+/a15_b0_de3.txt
+
A A 15
B B 5
D3 D3 3
X
FT runs_tab_angle_+/a15_b5_de3.txt
+
A A 15
B B 10
D3 D3 3
X
FT runs_tab_angle_+/a15_b10_de3.txt
+
A A 0
B B 5
D3 D3 4
X
FT runs_tab_angle_+/a0_b5_de4.txt
+
A A 0
B B 10
D3 D3 4
X
FT runs_tab_angle_+/a0_b10_de4.txt
+
A A 5
B B 0
D3 D3 4
X
FT runs_tab_angle_+/a5_b0_de4.txt
+
A A 5
B B 5
D3 D3 4
X
FT runs_tab_angle_+/a5_b5_de4.txt
+
A A 5
B B 10
D3 D3 4
X
FT runs_tab_angle_+/a5_b10_de4.txt
+
A A 10
B B 0
D3 D3 4
X
FT runs_tab_angle_+/a10_b0_de4.txt
+
A A 10
B B 5
D3 D3 4
X
FT runs_tab_angle_+/a10_b5_de4.txt
+
A A 10
B B 10
D3 D3 4
X
FT runs_tab_angle_+/a10_b10_de4.txt
+
A A 15
B B 0
D3 D3 4
X
FT runs_tab_angle_+/a15_b0_de4.txt
+
A A 15
B B 5
D3 D3 4
X
FT runs_tab_angle_+/a15_b5_de4.txt
+
A A 15
B B 10
D3 D3 4
X
FT runs_tab_angle_+/a15_b10_de4.txt

QUIT
