LOAD rocket_+.avl
OPER
A A 0
B B 0
X
FT runs_trial/A0_B0.txt
+
A A 5
B B 0
X
FT runs_trial/A5_B0.txt
+
A A 10
B B 0
X
FT runs_trial/A10_B0.txt
+
A A 15
B B 0
FT runs_trial/A15_B0.txt
+
A A 20
B B 0
FT runs_trial/A20_B0.txt
+
A A 25
B B 0
FT runs_trial/A25_B0.txt
+
A A 30
B B 0
FT runs_trial/A30_B0.txt
+
A A 35
B B 0
FT runs_trial/A35_B0.txt
+
A A 40
B B 0
FT runs_trial/A40_B0.txt
+
A A 45
B B 0
FT runs_trial/A45_B0.txt

QUIT
