
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          251382
     no. of nonzeroes in lower triangle of a =        15400809
     no. of nonzeroes in the factor l        =       103995440
     ratio of nonzeroes in factor (min/max)  =          0.4270
     number of super nodes                   =            7048
     maximum order of a front matrix         =            1476
     maximum size of a front matrix          =         1090026
     maximum size of a front trapezoid       =         1090026
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      6.4584D+10
     no. of floating point ops for solve     =      3.9666D+08
     ratio of flops for factor (min/max)     =          0.5617
     ratio of allocated memory (max/min)     =          2.5781
     number of positive pivots               =          251146
     number of negative pivots               =             236
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =              12
     number of threads per process used      =               1
     number of cores used                    =              12
     time (cpu & wall) for structure input   =        0.031250        0.018000
     time (cpu & wall) for ordering          =        0.734375        0.787000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.328125        0.345000
     time (cpu & wall) for numeric factor    =        0.734375        0.761000
     computational rate (gflops) for factor  =       87.944354       84.867457
     time (cpu & wall) for numeric solve     =        0.031250        0.026000
     computational rate (gflops) for solve   =       12.692967       15.255970
     effective I/O rate (GB/sec) for solve   =       47.288740       56.837428

     no input or output performed

  Solver Memory allocated on core    0       =      125.429 MB
  Solver Memory allocated on core    1       =      116.273 MB
  Solver Memory allocated on core    2       =       77.433 MB
  Solver Memory allocated on core    3       =       65.400 MB
  Solver Memory allocated on core    4       =      129.311 MB
  Solver Memory allocated on core    5       =      111.269 MB
  Solver Memory allocated on core    6       =      121.456 MB
  Solver Memory allocated on core    7       =      110.006 MB
  Solver Memory allocated on core    8       =      111.322 MB
  Solver Memory allocated on core    9       =       85.932 MB
  Solver Memory allocated on core   10       =      104.275 MB
  Solver Memory allocated on core   11       =      168.607 MB
  Total Solver Memory allocated by all cores =     1326.713 MB

