appendFile=true
dielectricMaterial=FR-4
fileName=laminate-03.odb
fileType=Laminate Layer (ODB++)
laminateLayerIndex=2
layerPolarity=POSITIVE
sourceFile=Z:/Developer/MIT_Rkt_Team/2026-7/MIT-RT-26_27-Work/simulation_work/avionics/powerboardsim/1/powerboardsim_v1_files/dp0/global/MECH/SYS/project/cca/laminate-03.odb
successMsg=
useLayerThickness=true
